# Generated by Django 4.2.5 on 2023-09-26 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacão', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=255)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('categoria_empresa', models.CharField(max_length=255)),
                ('quitado', models.BooleanField()),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Finecap.stand')),
            ],
        ),
    ]
